// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import Select2Controller from "./select2_controller"
application.register("select2", Select2Controller)

import AppearFormController from "./registration/appear_form_controller"
application.register("appear-form", AppearFormController)

import StepsController from "./steps_controller"
application.register("steps", StepsController)

import OtpController from "./otp_controller"
application.register("otp", OtpController)

import ValidationController from "./validation_controller"
application.register("validation", ValidationController)

import PasswordController from "./password_controller"
application.register("password", PasswordController)

import FormValidationController from "./forms/form_validation_controller"
application.register("form-validation", FormValidationController)

import SideMenuController from "./client/side_menu_controller"
application.register("side-menu", SideMenuController)